### ISSUE TITLE
needs content

### ISSUE THREAD

**Issue by ipc103** [learn-co-curriculum/sinatra-mvc-file-structure#1]
Refer to [Readme](https://github.com/learn-co-curriculum/sinatra-mvc-file-structure) for content to be included

due 9/17/2015 - using content from other repos here

**Comment by aviflombaum** [comment]
Reviewed. Really solid.

Minor diffs in README, mostly made sure code with this README worked should they clone it. https://github.com/learn-co-curriculum/sinatra-mvc-file-structure/commit/0fe309c178ce8bd00e8c59ea2e4fd556589a2035

Raising an issue re: how to tell the user that they should explore this Lesson's source code on github / locally because it includes examples. Technically, if that code is valuable to understand MVC, it should be described inline in the README.

**Comment by aviflombaum** [comment]
@AnnJohn you can mark as done.
