### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by asif-kamal** [learn-co-curriculum/sinatra-mvc-file-structure#32]
very slow loading.

**Comment by lizbur10** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the Learn.co curriculum.

This issue is being closed now as off-topic. If you still feel that this is an issue with the curriculum, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
